spring:
  application:
    name: gestion_turistica
  datasource:
    hikari:
      maximum-pool-size: 5
    #      connection-timeout: 10000
    database: ${MYSQL_DATABASE:gestion_turistica}
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        

upload:
  path:
    paquetes: C:/xampp/htdocs/Front/uploads/paquetes
    hoteles: C:/xampp/htdocs/Front/uploads/hoteles
    vaucher: C:/xampp/htdocs/Front/uploads/vouchers

  web:
    resources:
      static-locations: file:C:/xampp/htdocs/Front/uploads/



servlet:
 multipart:
  max-file-size: 10MB
  max-request-size: 10MB  


      
